added equilibira + some kientcis topics notes
cadalyjr/pchem_intro pull request #32
Opened 2022-07-15 20:02 UTC by Samgonza

Added some quick notes to the equilibria notes and kinetics subtopics, I'm not sure which topics should be included be highlighted or included. I could also add in steady state approximations or enzymes?

2022-07-19 01:36 UTC, cadalyjr commented
steady state approximations or enzymes are good ideas!

2022-07-19 01:38 UTC, cadalyjr requested changes
minor change - "No changes are observed at equilibrium." should be "No **overall** changes are observed at equilibrium."

2022-07-25 14:35 UTC, Samgonza commented
> minor change - "No changes are observed at equilibrium." should be "No **overall** changes are observed at equilibrium."

I made these changes to the file

2022-07-25 14:35 UTC, cadalyjr approved these changes

2022-07-25 14:55 UTC, merged